# Generated by Django 5.2.7 on 2025-10-15 08:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('owner', 'name')},
        ),
    ]
